version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: '17:00'
  open-pull-requests-limit: 10
  reviewers:
  - blacha
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '17:00'
  open-pull-requests-limit: 10
  reviewers:
  - blacha
  assignees:
  - blacha
